name: flutter_local_storage
description: "Local storage for keep data"
publish_to: none
version: 1.0.0
homepage:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #Storage
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.3
  hive:
    git:
      url: https://github.com/E-MRE/guki_hive/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  isar: ^4.0.0-dev.13

flutter:

